[package]
name = "berd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.18"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
